# SPDX-License-Identifier: LGPL-2.1-or-later

[Config]
MinimumVersion=25~devel

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=yes
Format=disk
ImageId=ParticleOS

[Content]
UnifiedKernelImageFormat=%i_%v
KernelCommandLine=rw

InitrdPackages=
    squashfs-tools
    tpm2-tools

Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        coreutils
        cpio
        curl
        dbus
        diffutils
        ubuntu-keyring
        dirmngr
        dmidecode
        dosfstools
        squashfs-tools
        findutils
        fish
        fwupd
        gdb
        grep
        gzip
        jq
        kbd
        kmod
        less
        libfido2-1
        man
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssl
        p11-kit
        pciutils
        pkcs11-provider
        polkitd
        sed
        socat
        strace
        efibootmgr
        systemd
        systemd-boot
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard
        xxd
        yubikey-manager
        zstd

[Validation]
SecureBoot=yes
SignExpectedPcr=yes

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
RuntimeScratch=no
