# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=ubuntu

[Distribution]
Release=oracular
Repositories=main,universe,multiverse

[Content]
Packages=
        adduser
        apparmor
        apt
        apt-utils
        base-files
        base-passwd
        bash
        bash-completion
        bind9-host
        bind9-libs
        ca-certificates
	    cpio
        curl
        dbus
        dbus-bin
        dbus-daemon
        dbus-session-bus-common
        dbus-system-bus-common
	    systemd-sysv
	    systemd-boot
        ca-certificates
        gpgv
	    grep
        systemd-sysv
        sysvinit-utils
	    e2fsprogs
        fdisk
        iproute2
        iputils-ping
        jq
        less
        login
        lsb-release
        locales
        netplan.io
        procps
        sudo
	    tzdata
        unzip
        vim
        linux-tools-common
        cryptsetup
        fido2-tools
        git
        cryptsetup
        iproute2
        iputils-arping
        iputils-ping
        iputils-tracepath
        iputils-clockdiff
        linux-generic-hwe-24.04
        libcap-ng-utils
        man-db
        openssh-client
        openssh-server
        libpam-runtime
        libpam-modules-bin
        libpam-modules
        libpam-doc
        passwd
        pcscd
        pcsc-tools
        python3
        libpam0g
        libpam-systemd
        systemd-homed
        sytemd-cryptsetup
        systemd-container
        systemd-ukify
        tpm2-tools
        tpm2-tss-engine-tools

